### ISSUE TITLE
Slow GDAL WMTS Raster layer

### ISSUE THREAD

**Issue by palmerj** [MapWindow/MapWinGIS#112]
Does anyway have any idea why adding and using this GDAL WMTS source as a raster layer is so slow? In QGIS the GDAL WMTS source loads for me in about 5secs, and each pan and zoom of the map on 1920x1200 screen takes about 3sec. But in the MapWinGIS control it's take x4-5 longer.

[wmts.xml.zip](https://github.com/MapWindow/MapWinGIS/files/2187316/wmts.xml.zip)

**Comment by pmeems** [comment]
Hi Jeremy,

I can confirm the slow behavior. I'm not sure why this is. Probably because the cache is not (properly) used.
We need to look into this.

We already have an JIRA issue about this: https://mapwindow.atlassian.net/browse/MWGIS-9
Now we need a developer with time to work on this. 
Are you by any change a C++ developer or do you have some budget so we can allocate a developer to work on this?

**Comment by palmerj** [comment]
> Are you by any change a C++ developer or do you have some budget so we can allocate a developer to work on this?

Very good questions. Yes I can development c++, but I would rather your devs did this. I've sent an email via your website to Dan. Is it possible for you to reply via this email request?

**Comment by JaqucesT** [comment]
I'm only a poor VBA-programmer, but the vb interface provides the parameter .TilesThreadPoolSize and changing this makes a huge difference in loading times of background tiles: More threads = faster loading.

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this old issue.
