### ISSUE TITLE
Union of shapefiles produces incorrect results

### ISSUE THREAD

**Issue by HollidayHT** [MapWindow/MapWinGIS#115]
When using the shapefile union function or using the overlay tool in MapWindow I am getting what I believe are invalid results. I have attached 2 shapefles (UseTest and SoilTest) and a shapefile resulting from the Union function (UseSoil_Union).

This is the line from my code.
        Dim spfUnion As Shapefile = spfUseTest.Union(False, spfSoilTest, False)

I don't believe the last 2 rows in the attributes table are correct. I get the same results from MapWindow using the overlay tool.

These are the attributes from the SoilTest file:
LABEL1
48
10
47
21
7

And these are the attributes for the UseTest file:
LABEL1
03
01
04
03
03
04
04
Site

The resulting shapefile does not appear correct:
LABEL1	LABEL1_1
03	10
01	7
01	21
01	47
01	10
01	48
04	47
04	48
03	10
03	10
04	10
04	48
Site	10
01	
	10

I believe the last 2 rows should be combined. The shapefiles overlay each other and shouldnt have any no intersecting shapes.

[ClipUnionTest.zip](https://github.com/MapWindow/MapWinGIS/files/2246448/ClipUnionTest.zip)

**Comment by HollidayHT** [comment]
The is becoming a critical issue for us. I have tried validating both input files in case invalid geometries were the cause but that doesn't seem to be the case. This error only happens on some shapes, the ones included in the zip file fail every time. I can catch this error but I haven't come up with a way to fix the resulting shapefile. Any assistance would be greatly appreciated.

**Comment by HollidayHT** [comment]
Did not mean to close this issue

**Comment by pmeems** [comment]
I did a quick look into this and I can confirm the mentioned behavior.
Something is definitely wrong with the two last shapes.

I created https://mapwindow.atlassian.net/browse/MWGIS-125 for this and will try to debug and fix it.

**Comment by pmeems** [comment]
It's taking a bit longer than expected.

We also just migrated from VS2013 to VS2015 and I'm having trouble registering the ocx.
I need to fix this before I can have a look at the union issue.

**Comment by pmeems** [comment]
The `Union()` method is implemented as a `Clip()` followed by a `Difference()` of sf1 with sf2 and then a `Difference()` of sf2 with sf1.
The mentioned last two shapes come from the two `Difference()` method.
That's why they are added and only the fields of one shapefile is filled.

![image](https://user-images.githubusercontent.com/12067729/44423726-1f5a9c00-a587-11e8-845a-18557bd12a72.png)
The yellow lines (small polygons) come from the difference between the soil and the use and the green lines come from the difference between the use and the soil.

To skip these small polygons you could change 

```
globalSettings.MinPolygonArea
globalSettings.MinAreaToPerimeterRatio
```
https://www.mapwindow.org/documentation/mapwingis4.9/class_global_settings.html#a9ac2289cc40bf76950bbf81f6a1ba953

I'll have a try with some values and let you know.

**Comment by pmeems** [comment]
First I run the union with the default values:
![image](https://user-images.githubusercontent.com/12067729/44425208-811d0500-a58b-11e8-8710-20a0cdcfcefc.png)
Then I can see what tresholds I need to use.

To skip the second-last shape I need to set the ratio to at least 0.021
That would also skip the last shape:

Resulting in:
![image](https://user-images.githubusercontent.com/12067729/44427545-2e931700-a592-11e8-9242-652f93e01c71.png)

**Comment by HollidayHT** [comment]
That explains why this seemed to intermitted. Adding the globalsetting options made this work for me.

Thank you for the help.

**Comment by HollidayHT** [comment]
This is still very much an issue for us changing the global setting parameters does seem to help on some simple polygons. I have attached to shapefiles that I cannot make merge correctly. Please let me know if you have any other ideas to try.

**Comment by pmeems** [comment]
You emailed me the reply. That doesn't work with attachments.
Could you attach the mentioned shapefiles to the GitHub issue?

**Comment by HollidayHT** [comment]
[RM_Use.zip](https://github.com/MapWindow/MapWinGIS/files/2405440/RM_Use.zip)
[RM_Soil.zip](https://github.com/MapWindow/MapWinGIS/files/2405441/RM_Soil.zip)

**Comment by HollidayHT** [comment]
Were you able to get the files I uploaded to GitHub?

**Comment by pmeems** [comment]
I have the files but have not found the time to have a look at them.
It is on top of my long TODO list.

**Comment by HollidayHT** [comment]
Is there any way this issue can be expedited? I would be happy to pay for any development time that would be required as this is a very pressing issue for our users.

Thanks

ToddH

**Comment by jerryfaust** [comment]
Hello @HollidayHT 
I should be able to help with this.  Let me review the history and I'll get back to you.
Regards.
Jerry.

**Comment by jerryfaust** [comment]
Hello @HollidayHT 

So I've been looking this over and reviewing the results.  And so far, I think they're OK.

I've tested using both the GEOS and Clipper libraries, and they both return results as shown below, with analysis as follows:  All combinations of polygons are returned, both for overlapping and non-overlapping areas.  When a label appears from both tables, it represents an overlapping area that existed in both layers.  When a label only appears from one table, it represents a polygon from one layer that did not overlap any portion of the other layer, but is still part of the result set.

As seen below, and can be verified, the small triangular region existed in polygon 10 from the SoilTest layer, but had no corresponding area (in other words, there was a hole) in the UseTest layer.  The other record returned (having a null value for LABEL1) in the result set corresponds to edges from the UseTest layer that exceeded the boundary of the SoilTest layer.  (This will also result when shared edges of adjoining polygons are not well aligned.)  And as @pmeems described earlier in this discussion, these sliver areas can be excluded, if you wish, by changing the MinAreaToPerimeterRatio setting.

![image](https://user-images.githubusercontent.com/30758167/51099433-84589d80-1785-11e9-874f-298238d87864.png)

So I'm not necessarily saying that this issue is settled, but I do think that in this particular case, it is just a matter of properly interpreting the results.  Please let me know if I am overlooking anything, or if there are other scenarios we need to verify.

Respectfully,
Jerry.

**Comment by HollidayHT** [comment]
I am still having issues with this and I believe it is related to the clip function. I have attached to shapefiles that overlap one another. I have validated the geometry in each one but I can’t clip the LandUse layer with the Parcel layer, no shapes are returned. Please let me know if you see the same issue.

Thank you very much for your time looking at this.

ToddH

**Comment by jerryfaust** [comment]
Hello @HollidayHT 

You mention 2 files that you have attached, Land Use and Parcels?  Are you referring to the RM_Use and RM_Soil?  Or are there other files I'm not seeing?

Thanks.
Jerry.

**Comment by HollidayHT** [comment]
There should have been an attached zip file called ClipTest. I have re-attached it, please let me know if it doesn’t make it there.

**Comment by jerryfaust** [comment]
I'm sorry @HollidayHT but there is no new attachment.  Are you replying to the email and attaching the file from there, or are you attaching the file within the GitHub Issue?  If you have not tried it, try attaching the file to the Issue within the GitHub website.

Regards.
Jerry.

**Comment by pmeems** [comment]
@HollidayHT Are you still having problems with this?

And be aware you're exposing your email address when you reply this comment via email.
It is better to go to GitHub and add a comment.

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
