### ISSUE TITLE
Can mapwingis support mbtiles data?

### ISSUE THREAD

**Issue by zcwbnu** [MapWindow/MapWinGIS#133]
Can MapWinGIS support mbtiles data? How to save online data to mbtiles, and how to use mbtiles offline?

**Comment by jerryfaust** [comment]
Hello @zcwbnu 

This will take a little more digging to determine the exact answer.  MapWinGIS uses the GDAL library for tile support, and the GDAL website indicates that it is 'capable' of loading mbtile data (via the SQLite driver), but not by default.  It may take a custom build of GDAL (and then a custom build of MapWinGIS) in order to add mbtile support.  @pmeems **Do you have any input on this?**

**Comment by pmeems** [comment]
I think @jerryfaust his analysis is correct. When GDAL supports mbtiles out of the box MapWinGIS should be able to read them as well.
Can you share a small sample file so we can check?

**Comment by zcwbnu** [comment]
Thank you! @jerryfaust  @pmeems  MapWinGIS stores data in db3 format, so how do I change it to mbtiles format？

**Comment by pmeems** [comment]
Do you still have problems with mbtiles?

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
