### ISSUE TITLE
Deployment error with a C# application

### ISSUE THREAD

**Issue by abrochet** [MapWindow/MapWinGIS#136]
Hello,

I tried to deploy MapWinGIS with a C# application but I have a problem :(

I used MapWinGIS as a COM component in Visual Studio after compiling my application I get two DLLs in the output directory:
- Interop.MapWinGIS.dll
- AxInterop.MapWinGIS.dll

When I launch my application on another PC I have an error related to the registration of the COM component.
How to deploy the application on another PC that is not a developer pc ... I did not find any information.

PI : I tried to add: MapWinGIS.ocx in the output directory of my application and saved it with regsvr32 except that I got an error, I think I missed something.

Thanks for your help

**Comment by jerryfaust** [comment]
Have you run the installer on the second machine?

[https://github.com/MapWindow/MapWinGIS/releases](https://github.com/MapWindow/MapWinGIS/releases)

**Comment by nguyenthetan1995** [comment]
On another computer, it is required to install the software mapwingis.exe

**Comment by abrochet** [comment]
No I did not install it on the other PC I thought that wasn't needed if it was using as a COM component!

I will try thank you.

**Comment by pmeems** [comment]
Please have a look at the install script for MapWindow5: https://github.com/MapWindow/MapWindow5/blob/master/install/MapWindow5.iss
Since WinXP-sp3 you no longer need to register MapWinGIS on the user PC. You need a manifest file and a subfolder with the MapWinGIS files.
The manifest file can/will be generated by Visual Studio.

And can you post future questions at our new forum: https://mapwindow.discourse.group/
So we can keep the issue list for defects.

**Comment by abrochet** [comment]
Hello,

Sorry for the late response, I was pretty busy.
Thanks for the link to the forum I would use it in the future if I have any questions ;)

I have ussed what you said: the manifest file and the DLLs directly into the bin directory.

Thanks for your help,
