### ISSUE TITLE
Need mapwingis.ocx 4.9.3.5

### ISSUE THREAD

**Issue by MOSSMONACO** [MapWindow/MapWinGIS#144]

**Comment by paulmeems-waterwatchfoundation** [comment]
Why would you need this very old version? 
I think it is worth the time to invest in the upgrade of your application to use the latest version of MapWinGIS.

**Comment by MOSSMONACO** [comment]
Hi Paul, thanks for the reply. Long ago I wrote a booking and dispatch
system which I sold to taxi companies. It originally was in vb5 but ended
up on vb6 / winxp / MS mappoint and has been very stable on that platform.
Since Mappoint has not had updated maps since 2010 its become necessary to
use a newer mapping system (also I hate mappoint with a passion- working
around its bugs and leaks took a long time). I have around 85 customer
machines that will want updating, all on XP, and taxi companies are not the
worlds best payers.....

**Comment by pmeems** [comment]
I did some searching and booted several old (virtual) machines but couldn't find any older versions than v4.9.4.2.
Then I remembered in the past MapWindow was also on the OSGeo-Live DVD.
They still have old copies online.
I could only find a very old version (v4.8): http://download.osgeo.org/livedvd/data/mapwindow/
I'm not sure if that version can do what you need, but at least you can give a try.

Since WinXP-sp3 you don't need to register MapWinGIS.ocx on the client computer, you can use a manifest file like we do now with MW5.
On your development computer you still need to install and register the x86 version to be able to use it in Visual Studio.

Hopefully this will solve your problem. But do remember, this version is over 7 years old!

Please use the forum (https://mapwindow.discourse.group/) if you have any more questions.

**Comment by MOSSMONACO** [comment]
THANK YOU, This looks promising!
