### ISSUE TITLE
How to open *.mwprj file

### ISSUE THREAD

**Issue by weskerjiang** [MapWindow/MapWinGIS#172]
Hello,how to open a *.mwprj file?Thanks

**Comment by jerryfaust** [comment]
Hello @weskerjiang 
Sorry for the delayed response.

That file extension is associated with the MapWindow application, a the Open Source GIS application built around the MapWinGIS OCX.  *.mwprj is from version 4 of the app, and *.mwproj is from version 5 of the app.

Just FYI, you are encouraged to ask questions like this [on the discussion forum](https://mapwindow.discourse.group/) rather than GitHub, which is moreso for Issues with the project.

Thank you.
