### ISSUE TITLE
Line marker style and ECW file bugs

### ISSUE THREAD

**Issue by NecroMancer05** [MapWindow/MapWinGIS#205]
Hi i can't open ECW file in the newer versions of MapWinGIS and MapWindow. And line marker style not working as expected. Thanks.

**Comment by jerryfaust** [comment]
Hello @NecroMancer05 

Here's a link to the issue on the MapWinGIS discourse site, regarding the [issue with ECW files](https://mapwindow.discourse.group/t/ecw-can-not-load/432/11).

As far as the line marker is concerned, you will have to be more specific, and possibly post some code that demonstrates the problem.  And for future reference, it's best to communicate on the discourse site rather than GitHub.

Regards,
Jerry.

**Comment by NecroMancer05** [comment]
Hello @jerryfaust 
Thanks for the response. Don't care about line marker bug it's my fault i did it. When i serialize/deserialize drawing styles i forget something.

I have one more question: i will publish my applicaton. its written in C# (windows form) and i am using lastest MapWinGIS build (x32). How i can make installer or i need to make some changes for make executable .exe file ?

**Comment by jerryfaust** [comment]
Hello.

I'm not sure I understand the question.  There are various applications that can generate an installer.  MapWinGIS uses [InnoSetup](https://jrsoftware.org/isinfo.php), which is a free installer-builder for Windows.  You could use that for your application as well, and incorporate the existing MapWinGIS installer into it.  Is that what you're asking?

Regards.

**Comment by NecroMancer05** [comment]
Hi,
We made a program like MapWindow. Based on C# winforms and MapWinGIS. I need to make installer like MapWindow, its contains all binaries, dlls and MapWinGIS build.
