### ISSUE TITLE
Opening ECW Files

### ISSUE THREAD

**Issue by NecroMancer05** [MapWindow/MapWinGIS#208]
Hi @pmeems ,

[Can u look at this](https://github.com/gisinternals/buildsystem/issues/154) there is progress on opening ECW files.

There is new ECW library in GDAL 3.1.2 VS2019 builds. When are we getting this update on MapWinGIS ?

**Comment by pmeems** [comment]
I just tried and I'm having trouble making MapWinGIS work with GDAL v3.*
That needs to be fixed first and then we need to move to VS2019, which hopefully won't be too hard and then we can create a new beta release.

@jbaux You've created a pull request to get MapWinGIS compiled using GDAL v3. I merged that PR and I can compile, but I can't register the ocx (`regsvr32 MapWinGIS.ocx`). Did you have similar issues?

@jerryfaust and @mathijs-dumon You both have much more experience with C++ than I. Do you have time to look how we can make MapWinGIS work with GDAL v3.*

**Comment by jerryfaust** [comment]
I can take a first-look and see what it involves; then we'll take it from
there.

Regards,
Jerry.

**Comment by pmeems** [comment]
Thanks @jerryfaust I did one more try and can now compile AND register. I missed 1 dll and didn't have the admin rights.
I'll commit my changes in a minute.

When running the InteropCreator project, which has a form with MapWinGIS on it, and hitting the 'Prefetch Tiles' button I get this error:
`GDAL FAILURE: PROJ: proj_create_from_database: Cannot find proj.db`
Most likely this has to do with proj 6.

In the following days I'll look more at this.

**Comment by jerryfaust** [comment]
Excellent.  Well done, Sir. Jerry From: Paul MeemsSent: Tuesday, February 9, 2021 8:50 AMTo: MapWindow/MapWinGISCc: Jerry Faust; MentionSubject: Re: [MapWindow/MapWinGIS] Opening ECW Files (#208) Thanks @jerryfaust I did one more try and can now compile AND register. I missed 1 dll and didn't have the admin rights.I'll commit my changes in a minute.When running the InteropCreator project, which has a form with MapWinGIS on it, and hitting the 'Prefetch Tiles' button I get this error:GDAL FAILURE: PROJ: proj_create_from_database: Cannot find proj.dbMost likely this has to do with proj 6.In the following days I'll more at this.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by NecroMancer05** [comment]
> I just tried and I'm having trouble making MapWinGIS work with GDAL v3.*
> That needs to be fixed first and then we need to move to VS2019, which hopefully won't be too hard and then we can create a new beta release.
> 
> @jbaux You've created a pull request to get MapWinGIS compiled using GDAL v3. I merged that PR and I can compile, but I can't register the ocx (`regsvr32 MapWinGIS.ocx`). Did you have similar issues?
> 
> @jerryfaust and @mathijs-dumon You both have much more experience with C++ than I. Do you have time to look how we can make MapWinGIS work with GDAL v3.*

I tried to compile too. But no hope i cant register it either.

**Comment by NecroMancer05** [comment]
Is where any news ?

**Comment by pmeems** [comment]
No news. At this moment the volunteers that have enough skills to get MapWinGIS to compile on VS2019 and working with GDAL v3 are too busy with their main jobs.

Until we can compile MapWinGIS with VS2019 we can't move on.
I tried, with my limited C++ skills, but couldn't get it to work.

For reference. We also have a discussion on our forum:
https://mapwindow.discourse.group/t/ecw-can-not-load/432/19
Perhaps it is better to continue the discussion on the forum.

**Comment by NecroMancer05** [comment]
Thanks for the reply.
