### ISSUE TITLE
Tiles display incorrect when the projection is not WGS84

### ISSUE THREAD

**Issue by ningfc** [MapWindow/MapWinGIS#214]
When I add a raster layer with reference that not the WGS 84 projection first , then I enable the tile layer, the tiles not re-project correctly, they are displayed overlay and had some gaps with each other.

I read the code about tile drawing, I think we need transform the tile image, not just calculate the start point and size of it.

Display like this.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/17332186/136967782-15f75920-2b5c-441e-87f5-c0300f3db83c.png">

**Comment by pmeems** [comment]
Sorry for the late reply. Questions like this can bet better asked on the forum: https://mapwindow.discourse.group/c/mapwingis/8

Tiles not in EPSG:3857 are projected on-the-fly. But because they are images they are only rotated resulting in the small gaps.
It is better to put your map in EPSG:3857, load the tiles and then open your shapefile. 
This shapefile will now be projected and the view should be much better.
