### ISSUE TITLE
CShapefileDrawer sfDrawer in Map_Drawing.cpp missing a param [zoom].

### ISSUE THREAD

**Issue by ningfc** [MapWindow/MapWinGIS#215]
I Found a Param missing problem in MapWinGIS code, at Map_Drawing.cpp CMapView::DrawLayers 
`
CShapefileDrawer sfDrawer(graphics, &_extents, _pixelPerProjectionX, _pixelPerProjectionY, &_collisionList, this->GetCurrentScale(), true);
`
This constructer miss a param zoom.
`
CShapefileDrawer drawer(g, &_extents, _pixelPerProjectionX, _pixelPerProjectionY, &_collisionList, GetCurrentScale(), GetCurrentZoom(), true);
`
This is used at other place in MapWinGIS Code, ti's correct.

**Comment by jerryfaust** [comment]
Hello @ningfc 

Yes, you are correct.  Looks like one of the developers added a new parameter to the constructor, but didn't catch all of the related calls.  And the compiler didn't catch it due to the last parameter being optional.

Thank you.  I'll try to get this fix incorporated.

Regards,
Jerry.

**Comment by jerryfaust** [comment]
Fixed in Jira issue [MWGIS-239](https://mapwindow.atlassian.net/browse/MWGIS-239).

**Comment by ningfc** [comment]
> Fixed in Jira issue [MWGIS-239](https://mapwindow.atlassian.net/browse/MWGIS-239).

OK, Thank you! I'll close this issue.
