### ISSUE TITLE
Point Type Icon: Transparency

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#43]
Hi,
I cannot apply an icon with a black background as a point type icon. The background becomes transparent.
Can someone please confirm this?
Thanks,
LT

**Comment by jerryfaust** [comment]
LT.

The default behavior for rendering Picture point types is to use the color of the top-left pixel as the transparency color.  This is not uncommon; ESRI libraries support this as well; and it allows for better rendering of image types that would not otherwise support transparency.

We can look at adding a flag to disable this feature; I tried setting UseTransparencyColor = False, but it did not change the behavior.

What I have done in the past, if you can edit the image, is to add a single pixel border around your image, using a color that is not used elsewhere in the image.  This new border will be interpreted as the transparency color, and your black background will then be visible.

Regards.
Jerry.

**Comment by ultraTCS** [comment]
Ok. Thanks for the feedback. 

I tried your suggestion but without success. I created a simple png - black filled square. and loaded it very simply as follows:

`MapWinGIS::IImagePtr mapImage;
mapImage.CreateInstance(__uuidof(MapWinGIS::Image));
 mapImage->Open("C:\\temp\\test.png", MapWinGIS::ImageType::USE_FILE_EXTENSION, VARIANT_FALSE, nullptr);
shapeFile->DefaultDrawingOptions->PutPicture(mapImage);
`

See attached result.
I've removed all other maps and drawing, yet still cannot get the black transparency removed from the image.
I've stepped thru the gdal source but can't quite find where the transparency is applied to the image.
If you can, please test with similar png point symbol. If you have any other insight, please share. Also if you can point me to the relevant source, that may help as well. I'm using 4.9.4.2.

TIA,
LT
![test_ss](https://user-images.githubusercontent.com/24417284/32793137-1b8c1de6-c933-11e7-9e0d-3707483e1297.PNG)

**Comment by jerryfaust** [comment]
LT.
I do have one more thing you can try.
I thought that I had tried this before, without success, but when I just tried it now, it worked.
I have an image with a black border, which was displaying transparently.
Instead of trying to turn off the transparency (UseTransparencyColor = False), I turned it on and set the transparency colors to Green (which is not in the image at all).  This is c# code, used for a category, but it should apply identically when specified for the default drawing options.

    cat.DrawingOptions.Picture.UseTransparencyColor = True
    cat.DrawingOptions.Picture.TransparencyColor = _utils.ColorByName(tkMapColor.Green)
    cat.DrawingOptions.Picture.TransparencyColor2 = _utils.ColorByName(tkMapColor.Green)

Both transparency colors have to be set (since the default color value is likely zero, which happens to be black).

Please let me know how this goes.  If it does not work, perhaps you could send me your image and I'll step through it to see why it behaves differently.

Regards.
Jerry.

**Comment by ultraTCS** [comment]
Thanks again Jerry. That did the trick.

I think the behaviour does need to change tho - as if you turn off the transparency (UseTransparencyColor = False), you should expect exactly that. It's counter-intuitive.

I assume this is in the GDAL drawing? Is there an implementation that MapWinGIS can override here?

**Comment by jerryfaust** [comment]
I agree, there's a bug there.  I'll need to step through it to see where it's breaking down.

Thanks for working with me on this.

**Comment by jerryfaust** [comment]
Update: The next release will have a fix for this, such that UseTransparencyColor = False will effectively ignore TransparencyColor and TransparencyColor2, and the image will be drawn as is, with no transparency being applied.

**Comment by ultraTCS** [comment]
excellent

**Comment by jerryfaust** [comment]
Update: The next release will have a fix for this, such that UseTransparencyColor = False will effectively ignore TransparencyColor and TransparencyColor2, and the image will be drawn as is, with no transparency being applied.

**Comment by jerryfaust** [comment]
As a follow-up, I was mistaken about automatically using the color of the top-left pixel for transparency.  But it's easy enough to do this if desired (particularly for BMP files, which do not natively support transparency).

cat.DrawingOptions.Picture.UseTransparencyColor = true;
cat.DrawingOptions.Picture.TransparencyColor = (uint)cat.DrawingOptions.Picture.get_Value(0, 0);
cat.DrawingOptions.Picture.TransparencyColor2 = cat.DrawingOptions.Picture.TransparencyColor;
