### ISSUE TITLE
 ocx registry

### ISSUE THREAD

**Issue by cpalominoch** [MapWindow/MapWinGIS#54]
Dear.
Please, how can it be done so that in my .net application I do not have to register the ocx?

Best regards.

Carlos Palomino.

**Comment by pmeems** [comment]
You can see how it is done in MW5. This .NET application is using a manifest file with all the necessary entries. Then you can just add the MapWinGIS files in a subfolder, without the need to register.

Keep in mind you still need to register MapWinGIS x86 on your development machine.

When you are creating your own .NET application you could also consider writing a plug-in for MW5 instead. Then you don't need to implement all the default stuff like the legend, category editor, shapefile editor, table editor, navigation, etc.

**Comment by krvax** [comment]
Hello everyone,

I'm having issues compiling my C# application with the MapWinGIS 64 bits version. I've been using the 32 bits version in order to develop my project, but now I can't  compile it.

What I've done is:
1. Install MapWinGIS 32 bits version.
2. Compile solution.
3. Uninstall 32 bits version.
4. Install 64 bits version.
5. Compile and run the solution.
>> Then I get an error: [ REGDB_E_CLASSNOTREG]

As far as I understand, this error is caused because it is not registered the MapWinGIS 32 bits version.

I've been searching in the documentation but have no success.

Any suggestions?

Any help would be appreciated.

Best regards.

**Comment by pmeems** [comment]
To compile you need the 32-Bit version of MapWinGIS because Visual Studio can't handle 64-bit ActiveX controls.
You can install both 32-bit and 64-bit version on your machine.
When you build your application for 32-bit, it should use the 32-bit version of MapWinGIS and when you build your application for 64-bit it should use the 64-bit version of MapWinGIS.

It is best not to build your application using 'Any CPU', then it is guessing which version is used.

And it is best not to hijack somebody else his post but ask new questions in new posts.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
