### ISSUE TITLE
google satellite provider.

### ISSUE THREAD

**Issue by imjoerock** [MapWindow/MapWinGIS#61]
Dear pmeems, would you pls advise how to add google satellite provider using the custom provider?. I try google satellite provider but not luck, may be url missmatch. Btw, bing satellite is not provide fine tiles in some area in my location.

**Comment by pmeems** [comment]
The Google Map providers have been removed due to changes in Google's license.
Here's some background info: https://mapwingis.codeplex.com/wikipage?title=googletiles
And here: https://developers.google.com/maps/faq#tos_tiles

In MapWinGIS (the actual mapping component of MW5) we still have a Google Tiles provider. But I just tested it and it is not working anymore.

So in short: It is not possible because it is not allowed anymore.
