### ISSUE TITLE
I use DrawLabelEx API crashed

### ISSUE THREAD

**Issue by zcwbnu** [MapWindow/MapWinGIS#65]
I use this code to display a label, it crashed, but I use DrawLine API correctly.
```
long layerNum = m_map.get_NumLayers();
long id = m_map.NewDrawing (1);
layerNum = m_map.get_NumLayers();
m_map.DrawLabelEx(id,"test",117.0, 39.0, 0);
```
Program crashed and I found the layerNum is same as  NewDrawing before. NewDrawing API not create drawing layer? I use mapwingis 4.9.4.2

**Comment by jerryfaust** [comment]
Hello @zcwbnu 
The drawing handles are different from the Layer handles, and that's why NumLayers does not change when starting a NewDrawing.
1. Can you send a little more context regarding the setup of your Map, for instance, the current projection settings?
2. You could also try starting a new drawing with screen coordinates instead of spatial coordinates, and putting the label up in the top corner, as follows, just to see if that works.
long id = m_map.NewDrawing(tkDrawReferenceList.dlSpatiallyReferencedList);
m_map.DrawLabelEx(id, "test", 100, 100, 0);
Thank you.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
