### ISSUE TITLE
Individual point style in edition mode

### ISSUE THREAD

**Issue by pierralex** [MapWindow/MapWinGIS#66]
Hello,
When editing some polylines i need to have a different color for some points with specific properties in my data model (it can be any of them). The only idea i found so far is to use another layer under the edited layer but i find that dirty and i am not sure the result will look good. Is there any "clean" way to do that?
Thanks,

**Comment by pmeems** [comment]
You're mixing a polygon layer with a  point layer. This is not recommended. 
You should create a point layer and copy the points of the polygons to it.
Then you can use different colors. 

You can also use a drawing layer (http://www.mapwindow.org/documentation/mapwingis4.9/group__map__drawing__layers.html) and only add the points when you select a polygon. 
A drawing layer is a kind of in-memory layer and it can mix points, lines, etc.

**Comment by pierralex** [comment]
Hi pmeems
I followed your advice. This is my method:
`axMap.ClearDrawing(drawHandle);`
 `drawHandle=axMap.NewDrawing(tkDrawReferenceList.dlSpatiallyReferencedList);`
`for (int i = 0; i <  n; ++i)`
`{`
`Point pt = axMap.ShapeEditor.RawData.Point[i];`
`axMap.DrawPoint(pt.x, pt.y, 15, RED_SHP);`
`}`

I called when starting the edition and on mouse moves.
But if i move a vertex too fast, the drawing layer shows the previous position of my mouse. I assume that axMap.ShapeEditor.RawData is updated after my mouse move event handler. Is there another way to get the current edited shape positions?

Best,

**Comment by pmeems** [comment]
I don't think so. I have not seen this use case before.

You have a polygon layer in edit mode. On top of this layer you have a drawing layer with the  vertices of the polygons as points and some points have different colors. Next you move a vertex of the polygon and want the drawing layer to be updated as well.
This is your use case?

Perhaps you can have a look at ShapeDrawingOptions: http://www.mapwindow.org/documentation/mapwingis4.9/class_shape_drawing_options.html
Then you can set the color of the vertices as well, instead of creating a new drawing layer.

First you create a category, using an expression you can make a subselection. Here's more info: http://www.mapwindow.org/documentation/mapwingis4.9/class_shapefile_category.html

**Comment by pierralex** [comment]
This is my use case. I just precise that I have 2 kind of points (normal and reference) which represent a trajectory . I can tag some  points as reference any time during the edition process.
My problem with this solution is that categories selection apply only to shapes. If i divide my trajectory in shapes, i get a discontinuous trajectory which is not acceptable.
Am I still missing something?

Best,

**Comment by pierralex** [comment]
I am using a drawing layer to override the color of the desired points as a workaround. It works quite well.
