### ISSUE TITLE
GeoProjection: bugs

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#91]
See attached patch file for a few minor bugs in this file.
[GeoProjection.cpp.txt](https://github.com/MapWindow/MapWinGIS/files/1929571/GeoProjection.cpp.txt)

**Comment by jerryfaust** [comment]
Thank you for your input @ultraTCS .

Sorry for the delayed response.  I have gone ahead and incorporated a couple of your changes.

The first one was already addressed in an earlier check-in, by casting the CString to LPCSTR, which is sufficient since we only need a const reference to the string.

```
	if (proj.GetLength() != 0)
	{
		fprintf(prjFile, "%s", (LPCSTR)proj);
	}

```
I will close this issue.

Regards.
Jerry.
