### ISSUE TITLE
In-memory Shapefile Polygon Drawing

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#94]
Hi, 

So there was an update made to _ShapefileDrawing.cpp_ for this bug:
[https://mapwindow.atlassian.net/browse/MWGIS-87](url)

Problem is it seems to have broken drawing when the `drawingMode` is `vdmGDIPlus`.
I don't know if the attached is a valid solution; however, it does fix the problem.

Thanks,
LT
[ShapefileDrawing.cpp.patch.txt](https://github.com/MapWindow/MapWinGIS/files/1956267/ShapefileDrawing.cpp.patch.txt)

**Comment by jerryfaust** [comment]
Hello @ultraLT 
I had thought those to be extraneous GetHDC and ReleaseHDC calls, but perhaps not.  Please tell me what exactly isn't working so that I can reproduce the problem and then verify if it is fixed.
Thank you.
Jerry

**Comment by ultraTCS** [comment]
Sorry its for the case that the drawingMode is `vdmGDIMixed`.
So set up a polygon shapefile and set drawing options such that line width is 1.
When you plot your points notice that the line is not plotted. Update line width > 1 and it works as the drawingMode becomes  `vdmGDIPlus`.

**Comment by pmeems** [comment]
@ultraLT Did you test you patch? Doesn't it introduce new memory leaks?
@jerryfaust Did you have a look at the patch?
If you both are fine with it, please apply the patch.

**Comment by ultraTCS** [comment]
Hi @jerryfaust ,
I think the patch I had submitted above is the same fix you applied for MWGIS-122?
Is that correct?
If so I can close this issue.
Thx.

**Comment by jerryfaust** [comment]
My apologies, @ultraLT ,
I knew someone had recently referenced this bug, but for some reason, I could not find it this weekend.  So I essentially had to re-discover the problem by stepping through it.  Your recommended patch was exactly the solution.  Thank you.  The issue can be closed.

@pmeems This does not re-introduce the memory leaks.  This particular change was supplemental to the primary memory leaks, and turned out to be erroneous and unnecessary.

**Comment by ultraTCS** [comment]
no apologies necessary!
